### ISSUE TITLE
Issue with StackClients resource using py4jps 1.0.35

### ISSUE THREAD

**Issue by markushofmeister** [cambridge-cares/TheWorldAvatar#800] opened 2023-06-21 09:09 UTC
The latest release of py4jps seems to affect how additional java resources are installed/loaded.

The `ForecastingAgent` uses both the JPSBaseLib and StackClients via py4jps. The agent image is build using the following Dockerfile, which includes the installation of the StackClients jar resource from another Docker image using jpsrm :
https://github.com/cambridge-cares/TheWorldAvatar/blob/hotfix-forecasting-agent/Agents/ForecastingAgent/Dockerfile

While this works well for `py4jps 1.0.34`, using version 1.0.35 fails. The image still builds successfully; however, when trying to launch the java gateway to the StackClients, a file not found error is raised.

**Comment by jb2197** [comment] 2023-06-22 00:56
> The `ForecastingAgent` uses both the JPSBaseLib and StackClients via py4jps. The agent image is build using the following Dockerfile, which includes the installation of the StackClients jar resource from another Docker image using jpsrm : https://github.com/cambridge-cares/TheWorldAvatar/blob/hotfix-forecasting-agent/Agents/ForecastingAgent/Dockerfile

Just to make sure the above link can still be resolvable should the PR gets merged, please refer to below instead: https://github.com/cambridge-cares/TheWorldAvatar/blob/4ed5df32d73eb1b9acbb93384995125f85c46725/Agents/ForecastingAgent/Dockerfile

**Comment by jb2197** [comment] 2023-06-23 20:53
Just for the record:

The root cause is the presence of the StackClients sub-folder in the `python_wrapper/py4jps/resources` directory of the machine I am making the release. This folder was left there from a previous installation of stack-client in the editable mode of py4jps in one of my environments. However, this folder was not included in the `python_wrapper/MANIFEST.in` file, which means that only the `StackClients.py` file is included in the py4jps 1.0.35 package on PyPI, but not the `.jar` files. (By default, `.jar` files are ignored unless explicitly specified in the MANIFEST.in file.) Due to the py file being present, the StackClients package is considered to exist in py4jps, which gives the "Info: Resource already exists" message when installing it from the Dockerfile (not actually installed) and subsequently the error encountered when calling it.

The short-term solution is https://github.com/cambridge-cares/TheWorldAvatar/pull/805. In the long run, we may want to consider the following suggestions at https://github.com/cambridge-cares/TheWorldAvatar/issues/360.

**Closed** 2023-07-04 07:53 UTC
Labels: bug, python-wrapper
