### ISSUE TITLE
Move stack images to GitHub

### ISSUE THREAD

**Issue by kok-foong** [cambridge-cares/TheWorldAvatar#786] opened 2023-06-12 04:15 UTC
At the moment pretty much all the stack functionalities rely on CMCL's server being online, the moment it goes offline we cannot do anything with the stack. It will be less disruptive for us in a different time zone if everything is on GitHub.

**Comment by sm453** [comment] 2023-06-12 08:08
See also #614.

**Comment by mdhillman** [comment] 2023-07-04 13:56
Closing as a duplicate of issue #614

**Comment by mdhillman** [comment] 2023-07-04 14:03
This related to issue #614, and is due to the fact that much of the code refers to older images. In most cases, new versions of these images exist and the import statement just needs updating. In some other cases, images need to be migrated from the CMCL registry to the GitHub one.

**Closed** 2023-09-26 13:00 UTC
Labels: good first issue, infra-stack
