### ISSUE TITLE
HTML characters in time series graph do not render correctly

### ISSUE THREAD

**Issue by kok-foong** [cambridge-cares/TheWorldAvatar#1044] opened 2023-12-12 02:47 UTC
Please look at screenshot
![image](https://github.com/cambridge-cares/TheWorldAvatar/assets/71323448/f2d3d8b0-be05-41a1-afab-7b851748ad35)

**Comment by mdhillman** [comment] 2023-12-12 09:48
Closing as a duplicate of issue #174.

**Closed by mdhillman** 2023-12-12 09:48 UTC
Labels: bug, infra-vis
