### ISSUE TITLE
Stack asking for Blazegraph credentials despite absent secrets file

### ISSUE THREAD

**Issue by markushofmeister** [cambridge-cares/TheWorldAvatar#601] opened 2023-02-13 12:00 UTC
I use the stack with a `postgres` and `geoserver` password as required; however, without a Blazegraph password. Sometimes when starting the stack (especially after crashing or becoming unresponsive), Blazegraph nevertheless starts up as password protected. This vanishes again mostly after running `bash .\stack.sh remove <stackname>` and a subsequent restart

**Comment by sm453** [comment] 2023-02-13 12:56
I have also observed this, occurring rather randomly. I have not found a way to consistently reproduce it.

**Comment by gpeb2** [comment] 2023-06-16 10:12
I've found the cause of the issue it's that if the Blazegraph password hasn't been specified by the user the `ContainerService::ensureOptionalSecret` method creates a dummy docker secret to keep the containers that are expecting one happy. The issue comes when the Blazegraph container is stopped without the dummy secret being removed as when it is started again it now thinks that there is a password set.

The short term solution is to always use the `./stack.sh rm` command to remove a stack as this will also remove the secrets.

The long term solution is to add a label to that secret marking it as being a dummy. This will require some changes to the `PodmanClient` as there have been issues adding labels to secrets in Podman in the past. I think those can be over come as we are now using the Podman API rather than their basic implementation of the Docker one to create secrets when running with Podman.

**Comment by gpeb2** [comment] 2023-06-16 10:26
The other solution is to just set a password.

**Closed** 2024-01-05 14:22 UTC
Labels: bug, infra-stack
